inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
  TargetRubyVersion: 2.3

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/ExtraSpacing:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
