language: ruby
sudo: false
# pick ruby version from .ruby-version
# rvm:
#   - 2.3.1
# Travis runs the following install command by default:
# install: bundle install --jobs=3 --retry=3
# make sure production gems not installed
bundler_args: --without production --jobs=3 --retry=3
# bundler cache isn't enabled by default
cache: bundler
script:
  - bundle exec rake lint
  - xvfb-run -a bundle exec rake spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare --trace
