default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  database: questions-service_<%= Rails.env %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default


production:
  <<: *default
  password: <%= ENV['QUESTIONS-SERVICE_DATABASE_PASSWORD'] %>
